### PR TITLE
integration.md: add sfwbar to the panels section

### PR DESCRIPTION
**Pull request by 01micko**

### CODE REVIEW

**Comment by 01micko** [comment]
That's better

**Comment by johanmalm** [comment]
Thanks. 
Any particular tips for configuring?
Isnt it this panel that defaults to the overlay lay (might remember wrong).
If so, we could suggest setting to top.

**Comment by 01micko** [comment]
I was thinking that we should link to the repo, there is plenty of info there, plus the default config will work for most OOTB. Probably should have a link to waybar too.

**Comment by LBCrion** [comment]
@johanmalm, sfwbar has been defaulting to the top layer since our last discussion.

**Comment by Consolatis** [comment]
> I was thinking that we should link to the repo

Agree. All panels are linked from the [README](https://github.com/labwc/labwc#6-integration) of the labwc repo. So we could either duplicate (all? just waybar + sfwbar?) panel links on the [website](https://labwc.github.io/integration.html#panels) or link to the README section there.

**Comment by 01micko** [comment]
Looks like `lavalauncher` is [officially abandoned](https://lists.sr.ht/~leon_plickat/lavalauncher/%3CCIPW63LE88JJ.2LYO5E6UAFLPB@m5%3E) and looking for a maintainer.

Not very welcoming for incomers if they see that at the top of the page. Should wee remove it from labwc/README?

I don't think it wise to add a link here.

**Comment by johanmalm** [comment]
> @johanmalm, sfwbar has been defaulting to the top layer since our last discussion.

Awesome. Sorry - my memory failed me :smile:

**Pull request merged**
