### PR TITLE
Fix menu font in man section

### PR DESCRIPTION
**Pull request by Consolatis**
I didn't rebuild the html pages because of the line-break issue.

### CODE REVIEW

**Comment by Consolatis** [comment]
Tried rebuilding with the latest pandoc installed but that one actually removed some part enclosed in GH code tags, e.g. \`
I am not sure what is going on here. We should likely stop running build-site ourselves, add the html files to .gitignore and set up a CI job for the build.

**Comment by johanmalm** [comment]
Does this one require a rebase?

**Comment by Consolatis** [comment]
yep, rebased

**Comment by Consolatis** [comment]
> Tried rebuilding with the latest pandoc installed but that one actually removed some part enclosed in GH code tags, e.g. ` I am not sure what is going on here. We should likely stop running build-site ourselves, add the html files to .gitignore and set up a CI job for the build.

Figured it out. Updated from scdoc `1.11.1` to ` 1.11.2` and the issue is fixed.

What do you think about this for the CI build?

```bash
#!/usr/bin/env bash


: ${DEPLOY_DIR:=.}
mkdir -p "$DEPLOY_DIR"

build_src_pages () {
	for md in src/*.md; do
		html=${md##*/}
		html="${DEPLOY_DIR}/${html/%.md/.html}"
		echo "Converting $md to $html"

		cat src/template_pre.html > "$html"
		pandoc --from=markdown+footnotes "$md" >> "$html"
		cat src/template_post.html >> "$html"
	done
}

build_man_pages () {
	git clone --branch master --depth 1 https://github.com/labwc/labwc labwc

	for scd in labwc/docs/*.scd; do
		html=${scd##*/}
		html="${DEPLOY_DIR}/${html/%.scd/.html}"
		echo "Converting $scd to $html"

		sed 's/sans-serif;/monospace;/' src/template_pre.html > "$html"
		scdoc < "$scd" |  pandoc --from man >> "$html"
		cat src/template_post.html >> "$html"
		./fix-bullet-formatting.py "$html"
	done
}

main () {
	build_src_pages
	build_man_pages
}

main "$@"
```

**Comment by johanmalm** [comment]
That’s great. Yes, familiar problem. Building with the latest pandoc seems to generally solve these things.
CI looks promising. 
Will we still be able to build html to view locally before pushing branches?

**Pull request merged**
