### PR TITLE
src/diagrams-theme.md: add menu description

### PR DESCRIPTION
**Pull request by 01micko**

### CODE REVIEW

**Comment by 01micko** [comment]
I just thought this might be handy :smile:

**Comment by 01micko** [comment]
BTW, drew it myself, here is the source:

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" height="1024px" width="1024px" viewBox="0 0 192 192">
  <style>
    .small {
      font: normal 6px sans-serif;
      fill:#808080;
    }  
  </style>
  <path style="fill:#0D1117;" d="m 0 0 192 0 0 192 -192 0 z"/>
  <path style="fill:none;stroke:#808080;stroke-width:1;" d="m 48 72 96 0 0 24 -96 0 z"/>
  <path style="fill:none;stroke:#808080;stroke-width:1;" d="m 48 96 96 0 0 24 -96 0 z"/>
  <path style="fill:#808080;stroke:#808080;stroke-width:1;" d="m 48 120 96 0 0 24 -96 0 z"/>
  <path style="fill:none;stroke:#808080;stroke-width:1;" d="m 48 144 96 0 0 24 -96 0 z"/>
  <path stroke-dasharray="0.2,0.2" style="fill:none;stroke:#808080;stroke-width:0.2;" d="m 96 12 -24 120 m 36 -96 -24 120"/>
  <text x="97" y="14" class="small">menu.items.active.bg.color</text>
  <text x="109" y="38" class="small">menu.items.bg.color</text>
</svg>
```

Depending on your default fonts it may look different, but I only have deja-vu installed so looks pretty consistent with `theme-window.png` when I converted to `png`.

**Comment by johanmalm** [comment]
Awesome. Thank you.

**Comment by 01micko** [comment]
You're welcome!

**Pull request merged**
