### PR TITLE
integration.md: add links for waybar,sfwbar; add yambar and link

### PR DESCRIPTION
**Pull request by 01micko**

### CODE REVIEW

**Comment by 01micko** [comment]
This is WIP. 
- where is the `waybar` stuff mentioned on this page edited?
- how is `waybar` started? If same as `sfwbar` and `yambar` should we simplify? eg:

> Panels are started in `~/.config/labwc/autostart` :
> ```
>  mypanel &
> ```

I'm open to ideas.

**Comment by johanmalm** [comment]
>     * where is the `waybar` stuff mentioned on this page edited?

`~/.config/waybar/config`

>     * how is `waybar` started? If same as `sfwbar` and `yambar` should we simplify? eg:

Yes, the same.


> > Panels are started in `~/.config/labwc/autostart` :
> > ```
> >  mypanel &
> > ```

Agree. Makes sense to just have one section describing how all panels are started.

It's worth mentioning that you can hide logging with this construct:

`mypanel >/dev/null 2>&1 &`

And people might find it useful to delay a panel to let other processes start first with something like this:

`( sleep 1 ; mypanel >/dev/null 2>&1 ) &`

By the way, I'm just catching up with notifications and pushed some `integration.md` notes on using xfce4-panel before seeing this. Hopefully not a problem, but it changes the number of your PR. Hope that's okay.

What are your thoughts on how 'deep' we go with `integration.md`?

**Comment by 01micko** [comment]
> Agree. Makes sense to just have one section describing how all panels are started.

I'm guessing this includes `xfce4-panel`

> `mypanel >/dev/null 2>&1 &` `labwc/docs/autostart`?

I'll change to that to be consistent with  `labwc/docs/autostart`

> `( sleep 1 ; mypanel >/dev/null 2>&1 ) &`

Yes, other options, but maybe that is for `labwc/docs/autostart`?

I think the depth should just be an introduction to new panels/menu-generators etc with basic 'get going' instructions and links to relevant docs.

I'll re-base this PR, with some changes, no problem.

**Comment by 01micko** [comment]
I think this is ready now.
- added link for xfce4-panel repo and fixed anchor link
- general panel starting instructions with link to `labwc/docs/autostart`
- links to man pages/docs (excepts xfce4-panel)
- checked all links working in firefox

**Comment by 01micko** [comment]
Darn! _Thought_ it was ready - **typo**!

**Comment by 01micko** [comment]
Made stuff a little more logical too.. is the horizontal line too much?

**Comment by johanmalm** [comment]
Thanks!

**Comment by 01micko** [comment]
Oh, I was about to push a horizontal line! Never mind. :laughing:

**Comment by 01micko** [comment]
I like it how it is anyway. Thank you too!

**Comment by johanmalm** [comment]
Oh. Whoops.
Think it looks good.
I see us gradually moving the integration section of README.md over to the website.

**Comment by Consolatis** [comment]
> Oh, I was about to push a horizontal line! Never mind. laughing

PR draft mode :)

**Pull request merged**
