### PR TITLE
Add tips-and-tricks page with notes on XML parsing

### PR DESCRIPTION
**Pull request by johanmalm**
...further to this discussion

https://github.com/labwc/labwc/pull/735#issuecomment-1416572447

@Consolatis  - does it read okay?

### CODE REVIEW

**Comment by Consolatis** [comment]
Yes looks about right

**Comment by Consolatis** [comment]
I've just read that [page](https://labwc.github.io/tips-and-tricks.html) again:

Do we want to remove the `To the end-user,` part?

**Comment by johanmalm** [comment]
Just those three words? Sure. I’m out of action for the next few days, but feel free 😄 

Or were you thinking the examples too?

**Comment by Consolatis** [comment]
> Or were you thinking the examples too?

I think the examples are perfectly fine, in my mind the end-user part just reads a bit strange.

> Just those three words? Sure. I’m out of action for the next few days, but feel free smile

Can't accept PR's in this repo, didn't try to just push though.

**Comment by johanmalm** [comment]
I can merge from phone :smile: if needed

**Pull request merged**
