### PR TITLE
add missing environment page

### PR DESCRIPTION
**Pull request by 01micko**
- fixes broken link in labwc/README.md

### CODE REVIEW

**Comment by johanmalm** [comment]
labwc-environment(5) man page does not exist anymore. There was so little left in it, that I swept it up in labwc-config(5)

To make changes/additions to this site, modify/add markdown files in src/ and run the build-site script. Don’t edit the top-level html files directly.

In the interest of trying to keep the source of truth/data in one place only, the build script auto-builds man pages based on what’s in the labwc repo itself.

**Comment by 01micko** [comment]
Of course, thanks.

Should we rather delete the link in `labwc/README.md`?

**Comment by johanmalm** [comment]
Whoops. Good catch.

**Comment by Consolatis** [comment]
Could this repo use some github action to build the new HTML whenever being pushed to?

**Comment by johanmalm** [comment]
Not sure if it is worth the faff - running the build-site script is so quick and simple.

The html files need to be committed in the repo for the website to exit (must be some internal github action because it normally takes a few seconds before they show on the website)

The build-script auto builds man pages. I find it useful to do this html conversion locally to before committing man pages to labwc repo.

pros: user does need pandoc installed (although probably want to generate hmtls locally anyway to see what is looks like?)

**Comment by Consolatis** [comment]
I don't have a strong opinion to either side, just wondered if it would ease contributions for users.

**Pull request closed without merging**
