### PR TITLE
Build and deploy page via CI

### PR DESCRIPTION
**Pull request by Consolatis**
This is the rough plan so far, the actual CI build isn't yet implemented. Still need to figure out how custom site pushes work.

~~Once we actually want to use this we'll likely have to change the repo config to deploy from the `main` branch and `deploy` directory but I didn't yet investigate all the details.~~ Doesn't look like we have to change that, but instead have to change something to use actions for deployments.

So what does this do so far?
- adds IRC notifications for issues / PRs, same as for the main repo
- deletes all compiled .html files
- creates a new `deploy` directory
- moves the `img` subfolder in there
- adds a new build.sh script which
  - clones the latest labwc
  - compiles all files into the new `deploy` directory
- adds  a .gitignore to ignore
  - `labwc/`
  - `deploy/*.html`
- splits the template file into a _pre and _post file

### CODE REVIEW

**Comment by Consolatis** [comment]
Ref: https://github.com/actions/upload-pages-artifact
Ref: https://github.com/actions/deploy-pages

**Comment by johanmalm** [comment]
Looks good.

Will the website with index.html in deploy/ ?
…and with deploy/*.html in .gitignore?

**Comment by Consolatis** [comment]
I've just tested the whole thing in my fork of the repo and it just worked and deployed the whole site to my personal gh page.
You'll have to change the deploy strategy for this repo to `GitHub Actions` (no further settings required on that page): Repo Settings -> Pages -> GitHub Actions
I think this is ready to go :)

I completely removed the old build-site script and replaced it with the new one:
- the filetime check is gone (but didn't actually work for me in the first place because on every change of the branch the HTML files would get a newer timestamp than the compiled man pages from labwc)
- all files will now be created in `deploy`, so just running `./build-site` like before should provide a complete preview in the new directory
- the workflow can also be run manually via the `Actions` tab if the need should arise.

**Comment by Consolatis** [comment]
Sweet, seems to work :)
https://github.com/labwc/labwc.github.io/actions/runs/4226331235

And https://labwc.github.io doesn't seem broken either + it was indeed rebuilt (can be seen on the menu font still being sans-serif even when in a man page.

So now just merging a PR with modification in src should automatically rebuilt the website and deploy them.

**Comment by johanmalm** [comment]
Yes. Amazing. I kept looking for the html files in deploy/ but it seems to work without them.

This is a really nice setup. Thanks for researching+implementing.

**Comment by Consolatis** [comment]
Now all that's left is to add another CI job to the main repo on pushes that checks of any of the new commits include changes to one of the man pages and if yes triggers a webhook in this repository which then automatically triggers the new CI job here.
This end of that call chain should already be set up correctly, I'll look into the sender part in the main repo in the next days.

**Comment by johanmalm** [comment]
Cool.
…and maybe add a paragraph in the readme to remind us how it works in a few weeks time - and for new devs

**Comment by Consolatis** [comment]
I could throw a README into .github/workflows/ for both repositories.

**Comment by johanmalm** [comment]
> I could throw a README into .github/workflows/ for both repositories.

That would ideal

**Comment by johanmalm** [comment]
PS. My IRC bouncer is down so can't connect at the moment.

**Comment by Consolatis** [comment]
Alright, will cook something up in the next days.

> PS. My IRC bouncer is down so can't connect at the moment.

Oh noes. Maybe sr.ht would be an alternative? I think they only offer bouncer accounts for paid members though, or maybe they would be up for supporting labwc with a bouncer account or two.

**Pull request merged**
