### PR TITLE
getting-started.md: fix image name

### PR DESCRIPTION
**Pull request by Flrian**

### CODE REVIEW

**Comment by Consolatis** [comment]
Thanks :)

**Comment by Consolatis** [comment]
No, its something with either GH or with how this repo is set up to run actions after accepting PRs.
Currently trying to figure out what is going on.

**Comment by Consolatis** [comment]
@johanmalm  This repo was set to build on "Deploy from a branch", changed it to "Github Actions".

So I assume what was happening is that whenever we accept a PR here we run some default python template engine and *also* our build and deploy workflow. Depending on timing its either one or the other that ends up being deployed.

Hopefully this is now fixed, we'll see when accepting the next PR.

**Comment by johanmalm** [comment]
Thanks both!

**Pull request merged**
