### PR TITLE
integration: add basic clipboard manager integration

### PR DESCRIPTION
**Pull request by 01micko**
references https://github.com/labwc/labwc/issues/2042

### CODE REVIEW

**Comment by xi** [comment]
I think there are two very different concerns here:

1. Users don't expect the clipboard to be lost when an application closes. This will affect (and probably annoy) most users. So it should be explained first and a simple, succinct solution should be provided.
2. Some users like to have more advanced clipboard managers that save a history and offer their own UI. These users generally don't expect this feature to just be there and therefore will actively search for it.

As far as I understand, your text is currently more geared towards the second group. Technically, it also solves the issue for the first group, but it is far more than what they want or expect. So the documentation of the proposed tools is more overwhelming than helpful.

**Comment by 01micko** [comment]
@xi 

While I agree with you about the first and second sentences of your first point, it is not only `labwc` in the wayland world that has this behaviour. 

---

What is not simple about .. 

> **Labwc** does not natively support storing of data kept on the clipboard.
For this functionality you need a _clipboard manager_.

The documentation I have written is meant as a guide only with relevant links. I don't think the page should have full explanations on every tool available for the job. Aside from that, each distro may have different packages, so I think full explanations should be part of distro documentation.

I've already slightly biased `cliphist`, as written in the `autostart` example and if anything, that's what I would be willing to change.

**Comment by xi** [comment]
To be clear, I don't actually like this solution. I think that it is strange to delegate such a crucial feature to external programs. It is also unfortunate that most clipboard managers suffer from feature creep. Some clipboard managers don't even have a mechanism to limit the number of history entries, which can quickly turn into a security issue. There is simply no good solution right now.

**Comment by 01micko** [comment]
@xi your comments are fair, but I fully understand why `labwc` refuses to manage the clipboard. In the `X` world there are a multitude of clipboard managers as well, many probably worse than what we have in wayland.

I'll take your advice on board about re-wording my PR but I'll wait for further review from maintainers before I change anything.

Thanks :)

**Comment by Consolatis** [comment]
> I was not meaning to propose that every available tool should be explained. I was merely suggesting to restructure the text to focus on the more common pain point:
> 
> > **Labwc** does not store clipboard contents after an application quits. For this functionality you need a _clipboard manager_.
> > For example, you could add a line similar to this to  `~/.config/labwc/autostart`:
> > ```
> > wl-paste --watch cliphist store &
> > ```
> > This uses [cliphist] and [wl-clipboard]. Other clipboard managers include  [clapboard] and [clipse].
> > Many clipboard managers have features beyond just keeping the clipboard alive. See the documentation of the individual tools for further information.

I like this variant, the current text might make users wonder if they need a clipboard manager or not while this one specifically mentions it being a solution to keep clipboard data after application close. I think this helps the user to evaluate the necessity of a clipboard manager and what might be problematic when running without one.

**Comment by johanmalm** [comment]
@01micko Thanks.

> I like this variant, the current text might make users wonder if they need a clipboard manager or not while this one specifically mentions it being a solution to keep clipboard data after application close. I think this helps the user to evaluate the necessity of a clipboard manager and what might be problematic when running without one.

Agree. @01micko if you're happy to update with this, we'll go for the merge.

**Comment by 01micko** [comment]
I'll update the PR tonight AEST.
Many thanks @Consolatis , @johanmalm and @xi for feedback.

**Comment by 01micko** [comment]
I just read through labwc/labwc/issues/2042

I won't have time to write up a page so I understand if this is closed.

**Comment by Consolatis** [comment]
> I won't have time to write up a page so I understand if this is closed.

No need for you to do that, I think the changes as proposed here are already very useful for users. We can always add a new page later on and then link it from the new section.

**Comment by Consolatis** [comment]
Thanks :)

**Pull request merged**
